### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxx/src/ASPIRER/AAidx.txt'

### ISSUE THREAD

**Issue by skeiii** [yanwu20/ASPIRER#1]
**There is an error occur when I run the command.**

 File "/home/xxxx/src/ASPIRER/ASPIRER.py", line 27, in <module>
    featureGenerator.generator(PSSM_file=args.PSSM_file, fasta_file=args.Fasta_file, output_name=args.output_name)
  File "/home/xxxx/src/ASPIRER/featureGenerator.py", line 74, in generator
    df_XGB = XGB_inputGenterator(fasta, **kw)
  File "/home/xxxx/src/ASPIRER/featureGenerator.py", line 50, in XGB_inputGenterator
    encoding = eval(cmd)
  File "<string>", line 1, in <module>
  File "/home/xxxx/src/ASPIRER/features_code/Moran.py", line 24, in Moran
    with open(fileAAidx) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxx/src/ASPIRER/AAidx.txt'

**I located where is the AAidx.txt, and it was in the /home/xxxx/src/ASPIRER/features_code/ folder, instead of ASPIRER.**

However, if I move the .txt file to ASPIRER, and rerun another error occur:
  File "/home/xxxx/src/ASPIRER/ASPIRER.py", line 27, in <module>
    featureGenerator.generator(PSSM_file=args.PSSM_file, fasta_file=args.Fasta_file, output_name=args.output_name)
  File "/home/xxxx/src/ASPIRER/featureGenerator.py", line 74, in generator
    df_XGB = XGB_inputGenterator(fasta, **kw)
  File "/home/xxxx/src/ASPIRER/featureGenerator.py", line 50, in XGB_inputGenterator
    encoding = eval(cmd)
  File "<string>", line 1, in <module>
  File "/home/xxxx/src/ASPIRER/features_code/Moran.py", line 44, in Moran
    AAidx1 = np.array([float(j) for i in AAidx for j in i])
  File "/home/xxxx/src/ASPIRER/features_code/Moran.py", line 44, in <listcomp>
    AAidx1 = np.array([float(j) for i in AAidx for j in i])
ValueError: could not convert string to float: 'NA'

**Comment by collinr2** [comment]
Hi, I did the same as you did you manage to find an answer to this? Also I was wondering if you knew what the threshold is supposed to be? Is it numeric or something I am supposed to make myself I am struggling to find it written down in the Github repository.

**Comment by skeiii** [comment]
> Hi, I did the same as you did you manage to find an answer to this? Also I was wondering if you knew what the threshold is supposed to be? Is it numeric or something I am supposed to make myself I am struggling to find it written down in the Github repository.

I was not able to find an answer to this. The threshold that I set is 0.5, but I have forgotten where I found this 0.5...

**Comment by yanwu20** [comment]
Please change the file path (ASPIRER/features_code/Moran.py line 22) to the path where AAindex.txt is located. 

Old 
`fileAAidx = re.sub('codes$', '', os.path.split(os.path.realpath(__file__))[0]) + r'\AAindex.txt' if platform.system() == 'Windows' else sys.path[0] + '/AAidx.txt'`
New:
`fileAAidx = /home/xxxx/src/ASPIRER/features_code/AAindex.txt`

**Comment by collinr2** [comment]
Hi, 

Thank you for your rapid response! I changed to the location of the AAindx.txt is located: 

fileAAidx = "/nesi/project/vuw03925/software/ASPIRER/ASPIRER/features_code/AAidx.txt"

However, I am still running into the same issue:

2024-03-20 10:43:15.785739: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "ASPIRER.py", line 26, in <module>
    featureGenerator.generator(PSSM_file=args.PSSM_file, fasta_file=args.Fasta_file, output_name=args.output_name)
  File "/scale_wlg_persistent/filesets/project/vuw03925/software/ASPIRER/ASPIRER/featureGenerator.py", line 76, in generator
    df_XGB = XGB_inputGenterator(fasta, **kw)
  File "/scale_wlg_persistent/filesets/project/vuw03925/software/ASPIRER/ASPIRER/featureGenerator.py", line 52, in XGB_inputGenterator
    encoding = eval(cmd)
  File "<string>", line 1, in <module>
  File "/scale_wlg_persistent/filesets/project/vuw03925/software/ASPIRER/ASPIRER/features_code/Moran.py", line 44, in Moran
    AAidx1 = np.array([float(j) for i in AAidx for j in i])
  File "/scale_wlg_persistent/filesets/project/vuw03925/software/ASPIRER/ASPIRER/features_code/Moran.py", line 44, in <listcomp>
    AAidx1 = np.array([float(j) for i in AAidx for j in i])
ValueError: could not convert string to float: 'NA'

Thank you again for your help!

**Comment by yanwu20** [comment]
Please try to use the AAindex.txt (not the AAidx.txt).

**Comment by collinr2** [comment]
Thank you !

**Comment by skeiii** [comment]
I still unable to use it.. 
a new error occur:

Traceback (most recent call last):
  File "/home/xxxx/src/ASPIRER/ASPIRER.py", line 7, in <module>
    import featureGenerator
  File "/home/xxxx/src/ASPIRER/featureGenerator.py", line 7, in <module>
    from features_code import *
  File "/home/xxxx/src/ASPIRER/features_code/Moran.py", line 22
    fileAAidx = /home/xxxx/src/ASPIRER/features_code/AAindex.txt
                                                                                                               ^
IndentationError: unindent does not match any outer indentation level
